[package]
name = "mazzarothd"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = { path = "../utils" }
consensus = { path = "../consensus" }
mvm = { path = "../mvm" }
database = { path = "../database" }
mining = { path = "../mining" }

serde = { workspace = true }
tokio = {workspace = true}
anyhow = {workspace = true}
axum = {workspace = true}
reed-solomon-erasure = {workspace = true}
alloy-rlp = { workspace = true }
log = { workspace = true }
crossbeam = { workspace = true }

[features]
disable_storage_limit = []
