[package]
name = "mvm"
version = "0.1.0"
edition = "2024"

[dependencies]
consensus = { path = "../consensus" }
utils = { path = "../utils" }

serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
sha2 = { workspace = true }
alloy-rlp = { workspace = true }

[features]
disable_storage_limit = []